<a href="https://colab.research.google.com/github/PercyTechX/del-excel-al-ml/blob/main/temporada-0/04-pandas-abre-tu-excel/clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab"/></a>

# Episodio 0.4 · pandas I: abre tu Excel en Python

**Serie:** Del Excel al Machine Learning · **Temporada 0** · 🎬 Video próximamente

## 🎯 Qué vas a aprender

- Abrir archivos CSV y Excel con **pandas**.
- Mirar una tabla y elegir sus columnas.
- **Filtrar** filas, como con el embudo de Excel.
- **Ordenar** de mayor a menor.

## 📊 En Excel lo harías así

Te piden las ventas más grandes de Lima, de un archivo con 50 mil filas:

1. **Abres** el archivo.
2. Activas los **filtros** y eliges `Lima` en la columna `ciudad`.
3. **Ordenas** la columna `total` de mayor a menor.

En Python son los mismos pasos, más uno: quedarte con las columnas que te interesan. Y quedan escritos: el próximo mes solo vuelves a ejecutarlos.

## 🐍 En Python

### Paso 1: abrir un archivo

**pandas** es la herramienta de Python para trabajar con tablas. Colab ya la trae instalada; solo hay que llamarla con `import`. Le decimos `pd` para escribir menos.

Abajo también guardamos la dirección de internet donde están los datos del curso:

In [1]:
import pandas as pd

DATOS = "https://raw.githubusercontent.com/PercyTechX/del-excel-al-ml/main/datos/"

Un **CSV** es una tabla guardada como texto, con los datos separados por comas. `pd.read_csv()` lo abre, y lo guardamos en una variable. Con `+` unimos dos textos: la dirección y el nombre del archivo. A esta tabla, pandas la llama **DataFrame**: es como una hoja de Excel.

`.head()` muestra las primeras 5 filas y `.shape` dice cuántas filas y columnas tiene. `.shape` es un dato y `.head()` una acción: por eso solo esta lleva paréntesis.

In [2]:
ventas = pd.read_csv(DATOS + "ventas.csv")

print(ventas.shape)
ventas.head()

(50000, 11)

,id_venta,fecha,id_cliente,id_producto,id_vendedor,ciudad,cantidad,precio_unitario,descuento,total,metodo_pago
0,V000001,2024-01-02,C0002,P022,E006,Arequipa,3,48.0,0.0,144.0,Efectivo
1,V000002,2024-01-02,C0003,P045,E004,Lima,2,46.0,0.0,92.0,Billetera digital
2,V000003,2024-01-02,C0008,P021,E010,Chiclayo,3,46.0,0.0,138.0,Efectivo
3,V000004,2024-01-02,C0022,P046,E007,Trujillo,9,70.0,0.0,630.0,Efectivo
4,V000005,2024-01-02,C0024,P021,E013,Cusco,6,46.0,0.0,276.0,Crédito

> 💡 Los números en negrita de la izquierda son el **índice**: identifican cada fila, como los números de fila de Excel. Empiezan en 0, igual que las listas.

Para un libro de Excel, usa `pd.read_excel()` e indica la hoja con `sheet_name`. Sin esa opción, abre la primera hoja. Dentro de los paréntesis, `=` indica una opción, no guarda nada.

In [3]:
productos = pd.read_excel(DATOS + "reporte_ventas_2025.xlsx", sheet_name="Productos")

productos.head()

,id_producto,categoria,nombre,marca,presentacion,precio,costo
0,P001,Abarrotes,Arroz extra 5 kg,Valle Dorado,Fardo x 5,99.5,85.21
1,P002,Abarrotes,Arroz superior 1 kg,Valle Dorado,Fardo x 10,42.0,35.96
2,P003,Abarrotes,Azúcar rubia 1 kg,Cumbre,Fardo x 10,39.0,35.59
3,P004,Abarrotes,Aceite vegetal 1 L,Sol del Sur,Caja x 12,105.0,91.38
4,P005,Abarrotes,Fideos spaghetti 500 g,Nonna Lucía,Fardo x 20,56.0,50.73

#### Para después del video: tus propios archivos

Tienes dos caminos:

- **Subirlo a la carpeta 📁**, como en el episodio 0.1, y escribir solo su nombre: `pd.read_excel("mi_archivo.xlsx")`. Recuerda que es temporal.
- **Conectar tu Google Drive**, para que no se borre. Copia esto en una celda nueva, ejecútalo una vez por sesión y acepta los permisos:

```python
from google.colab import drive

drive.mount("/content/drive")
```

Luego lo abres con su ruta, que empieza así: `pd.read_excel("/content/drive/MyDrive/mi_archivo.xlsx")`. Para copiar la ruta exacta, haz clic derecho en el archivo, dentro de 📁, y elige **Copiar ruta**. Si es un Google Sheets, descárgalo primero como `.xlsx`.

Si tu CSV se abre en una sola columna o da un `ParserError`, seguramente está separado por punto y coma. Lo resolvemos en el episodio 0.5.

### Paso 2: elegir columnas

Una columna se pide como un dato de un diccionario, con su nombre entre corchetes:

In [4]:
ventas["ciudad"].head()

0    Arequipa
1        Lima
2    Chiclayo
3    Trujillo
4       Cusco
Name: ciudad, dtype: object

Para pedir varias, pon una **lista** de nombres; por eso salen dos pares de corchetes. Con un solo par, verás un `KeyError`.

In [5]:
ventas[["fecha", "ciudad", "total"]].head()

        fecha    ciudad  total
0  2024-01-02  Arequipa  144.0
1  2024-01-02      Lima   92.0
2  2024-01-02  Chiclayo  138.0
3  2024-01-02  Trujillo  630.0
4  2024-01-02     Cusco  276.0

### Paso 3: filtrar filas

Imagina que en Excel agregas una columna con `=F2="Lima"`, que dice `VERDADERO` o `FALSO` en cada fila. pandas hace lo mismo con la comparación que viste en el episodio 0.3:

In [6]:
(ventas["ciudad"] == "Lima").head()

0    False
1     True
2    False
3    False
4    False
Name: ciudad, dtype: bool

`True` es verdadero y `False` es falso (por eso dice `bool`, el tipo de esos valores). Si metes esa comparación entre corchetes, pandas se queda solo con las filas `True`. Eso es un filtro:

In [7]:
ventas_lima = ventas[ventas["ciudad"] == "Lima"]

print(ventas_lima.shape)
ventas_lima.head()

(19423, 11)

,id_venta,fecha,id_cliente,id_producto,id_vendedor,ciudad,cantidad,precio_unitario,descuento,total,metodo_pago
1,V000002,2024-01-02,C0003,P045,E004,Lima,2,46.0,0.0,92.00,Billetera digital
9,V000010,2024-01-02,C0069,P035,E003,Lima,2,102.0,0.0,204.00,Crédito
10,V000011,2024-01-02,C0073,P016,E001,Lima,21,16.5,0.1,311.85,Crédito
11,V000012,2024-01-02,C0074,P017,E004,Lima,2,16.8,0.0,33.60,Billetera digital
12,V000013,2024-01-02,C0075,P048,E002,Lima,3,50.0,0.0,150.00,Transferencia

Los saltos en el índice son normales: cada fila conserva su número, como cuando filtras en Excel.

> ⚠️ Si tu filtro da 0 filas, no hay ningún error que te avise. Revisa mayúsculas, tildes y espacios: `"lima"` no es `"Lima"`.

Para **dos condiciones**, cada una va entre paréntesis y se unen con `&`, que equivale a `=Y()` (`AND`). No es el `&` de Excel que une textos. Para `=O()` (`OR`), se usa `|`.

> ⚠️ Aquí no sirven el `and` y el `or` del episodio 0.3: con tablas dan un `ValueError`. Y si olvidas los paréntesis, verás un `TypeError` con la palabra `rand_`.

In [8]:
grandes_lima = ventas[(ventas["ciudad"] == "Lima") & (ventas["total"] >= 1000)]

grandes_lima.shape

(526, 11)

### Paso 4: ordenar

`.sort_values()` ordena por una columna. Con `ascending=False` va de mayor a menor. Y se puede encadenar con `.head()` para ver solo las primeras filas:

In [9]:
ventas_lima.sort_values("total", ascending=False).head()

,id_venta,fecha,id_cliente,id_producto,id_vendedor,ciudad,cantidad,precio_unitario,descuento,total,metodo_pago
24414,V024415,2025-01-03,C0109,P036,E003,Lima,26,150.0,0.10,3510.00,Crédito
13957,V013958,2024-08-07,C0010,P001,E002,Lima,39,99.5,0.10,3492.45,Billetera digital
1894,V001895,2024-02-06,C0104,P037,E002,Lima,19,155.0,0.05,2797.75,Billetera digital
2201,V002202,2024-02-11,C0206,P037,E003,Lima,19,155.0,0.05,2797.75,Crédito
8874,V008875,2024-05-29,C0231,P036,E002,Lima,19,150.0,0.05,2707.50,Transferencia

Al ordenar, cada fila también conserva su número. Excel, en cambio, renumera.

> ⚠️ A diferencia de Excel, filtrar y ordenar **no cambian tu tabla original**: crean una tabla nueva. Si quieres conservarla, guárdala en una variable, como hicimos con `ventas_lima`.

### Todo junto

Las ventas más grandes de Lima, con las columnas que nos interesan. Es el pedido del inicio. Como `columnas` ya es una lista, aquí basta un par de corchetes:

In [10]:
columnas = ["fecha", "id_producto", "cantidad", "total"]

ventas_lima.sort_values("total", ascending=False)[columnas].head()

            fecha id_producto  cantidad    total
24414  2025-01-03        P036        26  3510.00
13957  2024-08-07        P001        39  3492.45
1894   2024-02-06        P037        19  2797.75
2201   2024-02-11        P037        19  2797.75
8874   2024-05-29        P036        19  2707.50

## 🤖 Pídeselo a la IA

Cuéntale qué columnas tiene tu tabla y qué filtro necesitas. Por ejemplo, en Gemini:

> *"Tengo un DataFrame llamado `ventas` con las columnas `ciudad`, `metodo_pago` y `total`. Muéstrame cómo filtrar las ventas de Piura con `metodo_pago` igual a `Transferencia`, y explícame cada parte."*

La IA te ayuda a escribir y entender código, pero **tú debes entender lo que hace**. Revisa cada respuesta antes de usarla.

## ✅ Resumen

| En Excel | En Python |
|---|---|
| Abrir un CSV | `pd.read_csv("archivo.csv")` |
| Abrir una hoja de un libro | `pd.read_excel("libro.xlsx", sheet_name="Hoja")` |
| Una hoja | Un DataFrame |
| Mirar las primeras filas | `ventas.head()` |
| Ver cuántas filas y columnas hay | `ventas.shape` |
| Quedarte con algunas columnas | `ventas[["fecha", "total"]]` |
| Filtrar | `ventas[ventas["ciudad"] == "Lima"]` |
| `=Y()` (`AND`) en un filtro | `ventas[(condición 1) & (condición 2)]` |
| `=O()` (`OR`) en un filtro | `ventas[(condición 1) \| (condición 2)]` |
| Ordenar de mayor a menor | `ventas.sort_values("total", ascending=False)` |

## 📝 Ahora te toca

Abre [el ejercicio en Colab](https://colab.research.google.com/github/PercyTechX/del-excel-al-ml/blob/main/temporada-0/04-pandas-abre-tu-excel/ejercicio.ipynb) y practica. Cuando termines, compara con [la solución](https://colab.research.google.com/github/PercyTechX/del-excel-al-ml/blob/main/temporada-0/04-pandas-abre-tu-excel/solucion.ipynb).

---

*Del Excel al Machine Learning* · por [Percy Nazario](https://www.linkedin.com/in/percy-nazario/) · [Repositorio](https://github.com/PercyTechX/del-excel-al-ml) · Contenido bajo licencia CC BY 4.0